spring.application.name=ecommerce-backend

server.port=8080


# =========================
# Database - MySQL RDS
# =========================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/ecommerce?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Hoangtoi2004}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================
# JPA / Hibernate
# =========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# =========================
# Admin
# =========================

app.admin.username=${ADMIN_USERNAME:ADMIN}

app.admin.password=${ADMIN_PASSWORD:toihoang}


# =========================
# Mail / Amazon SES
# =========================

app.mail.enabled=${MAIL_ENABLED:true}

app.ses.region=${APP_SES_REGION:ap-southeast-1}
app.ses.from-email=${APP_SES_FROM_EMAIL:toih1204@gmail.com}


# =========================
# AWS S3
# =========================

app.s3.bucket-name=${APP_S3_BUCKET_NAME:techmart-product-images-1204}

app.s3.region=${APP_S3_REGION:ap-southeast-1}

app.s3.presigned-url-expiration-minutes=${APP_S3_PRESIGNED_URL_EXPIRATION_MINUTES:60}